### ISSUE TITLE
systemd changed in haproxy 1.8.8

### ISSUE THREAD

**Issue by tiago-cruz-movile** [fabianlee/blogcode#1]
hey man!

nice article yours in https://fabianlee.org/2017/10/16/haproxy-zero-downtime-reloads-with-haproxy-1-8-on-ubuntu-16-04-with-systemd/

but didn't work for me in newers versions of haproxy (1.8.8)

is better to use the systemd file `contrib/systemd/haproxy.service.in` that comes with haproxy, cause there is some changes:

```
[Service]
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid"
ExecStartPre=@SBINDIR@/haproxy -f $CONFIG -c -q
ExecStart=@SBINDIR@/haproxy -Ws -f $CONFIG -p $PIDFILE
ExecReload=@SBINDIR@/haproxy -f $CONFIG -c -q
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed
Restart=always
Type=notify
```

https://www.mail-archive.com/haproxy@formilux.org/msg28587.html

Quote from Lukas Tribus:

"Your systemd configuration is not uptodate.

Please:
- make sure haproxy is compiled with USE_SYSTEMD=1
- update the unit file: start haproxy with -Ws instead of -W (ExecStart)
- update the unit file: use Type=notify instead of Type=forking"

**Comment by fabianlee** [comment]
Really appreciate the feedback! sorry it took so long to change. I now use the haproxy.service file distributed with the ppa and use sed to make a slight modification to remove the start rate limit (instead of using my own file).
