### ISSUE TITLE
Jib instead of Palantir for making Java based containers

### ISSUE THREAD

**Issue by gavenkoa** [fabianlee/blogcode#4]
Reaction to https://fabianlee.org/2022/06/30/java-creating-docker-image-for-spring-boot-web-app-using-gradle/

For Java containers the https://github.com/GoogleContainerTools/jib is better.

OCI images are "simple" TAR archives, it is strange that we depended on Docker for a long time. JIB allows to create OCI image without dependensies on image execution runtimes. Gradle/Maven plugin is included, allowing OCI image creation and publishing to registry. At the end the buid is more build pipeline "friendly" (no extra requirement on running Docker, no privileged containers, etc).

**Comment by fabianlee** [comment]
did the following write up for jib
https://fabianlee.org/2022/07/03/java-oci-compatible-image-for-spring-boot-web-app-using-jib/
