### ISSUE TITLE
Count numbers without "echo -e"

### ISSUE THREAD

**Issue by gavenkoa** [fabianlee/blogcode#5]
Reaction to https://fabianlee.org/2021/08/22/bash-count-number-of-lines-in-previously-captured-stdout/

`echo -ne` is smelly. Use `printf` instead (POSIX portable). And with Bash you can use magic syntax `$'a\nb\n'` and HERE-WORD (avoiding fork on pipe with `echo`??):

```sh
v=$'a\nb\nc\nd'
wc -l <<<$v
```

**Comment by fabianlee** [comment]
resolved
